/**
 * Bundle the action into a single self-contained ESM file at `dist/index.js`.
 *
 * GitHub Actions does not run `npm install` for JavaScript actions — it executes
 * the committed `dist/index.js` directly — so every dependency must be inlined.
 * That is why `dist/` is committed and why CI verifies it matches the sources.
 *
 * esbuild rather than ncc: `@actions/core` v3 and `@actions/github` v9 are
 * ESM-only, and esbuild bundles ESM to ESM natively while ncc's bundled
 * ts-loader does not support the current TypeScript release.
 */
import { build, context as createContext } from 'esbuild';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import * as path from 'node:path';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

/** Must stay consistent with `runs.using` in action.yml and `engines.node`. */
const NODE_TARGET = 'node22';

const ENTRY = path.join(rootDir, 'src/main.ts');
const OUTFILE = path.join(rootDir, 'dist/index.js');

/**
 * Restore a working `require` in the ESM bundle.
 *
 * Transitive CommonJS dependencies still call `require('net')` and friends
 * (`tunnel`, reached through `@actions/http-client`). In an ESM output esbuild
 * replaces those with a shim that throws "Dynamic require ... is not supported",
 * which fails at action startup. esbuild's shim defers to a global `require`
 * when one exists, so defining a real one here makes those calls work.
 */
const BANNER = [
  '// Generated by scripts/build.mjs — do not edit. Run `npm run build` after changing src.',
  "import { createRequire as __blastRadiusCreateRequire } from 'node:module';",
  'const require = __blastRadiusCreateRequire(import.meta.url);',
].join('\n');

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [ENTRY],
  outfile: OUTFILE,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: NODE_TARGET,
  sourcemap: true,
  // Action logs surface the bundle's own stack traces; keep them readable.
  minify: false,
  treeShaking: true,
  legalComments: 'external',
  logLevel: 'warning',
  banner: { js: BANNER },
};

if (process.argv.includes('--watch')) {
  const ctx = await createContext(options);
  await ctx.watch();
  console.log('watching src/ — rebuilding dist/index.js on change');
} else {
  const result = await build({ ...options, metafile: true });
  const { byteLength } = await readFile(OUTFILE);
  const moduleCount = Object.keys(result.metafile.inputs).length;
  console.log(
    `dist/index.js  ${(byteLength / 1024).toFixed(0)} kB  from ${moduleCount} modules  (target ${NODE_TARGET})`,
  );
}
